# Autogenerated by devscripts/update-version.py

__version__ = '0.0.3.0'

RELEASE_GIT_HEAD = '6b44bdd32edf7a7c3ea8af2d67a68cd85ffe9134'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '0.0.3.0'
