# Autogenerated by devscripts/update-version.py

__version__ = '0.0.2.0'

RELEASE_GIT_HEAD = '801e9bbdfb06774457a821e9e11d36f8f6cfae50'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '0.0.2.0'
