# Autogenerated by devscripts/update-version.py

__version__ = '0.0.2.1'

RELEASE_GIT_HEAD = 'cd71ced0af931f7f1f620e1b529a221cc8c36f47'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '0.0.2.1'
